version: '3'

services:
  app:
    build: .
    container_name: astro-sarafan
    depends_on:
      - postgres
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    volumes:
      - ./config/config.yaml:/app/config.yaml
      - pdf_data:/app/data/pdf
    ports:
      - "8080:8080"

  postgres:
    image: postgres:15
    container_name: astro-sarafan-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrations/migration_button_reminder.sql:/docker-entrypoint-initdb.d/migration_button_reminder.sql
    ports:
      - "15432:5432"

volumes:
  postgres_data:
  pdf_data: