version: '3'

services:
  app:
    build: .
    container_name: astro-sarafan1
    depends_on:
      - postgres
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    volumes:
      - ./config/config.yaml:/app/config.yaml

  postgres:
    image: postgres:15
    container_name: astro-sarafan-database1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/app/migrations
    ports:
      - "54321:5432"

volumes:
  postgres_data:
