telegram:
  token: "7565405696:AAELJ7RISzLoqYPLvdvlBu8P6njDP0Gflk4"
  astrologer_channel: "2605944399"

log:
  level: "debug"
  sink: "stdout"

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "astro_sarafan"
  sslmode: "disable"