telegram:
  token: "7925395356:AAGEi53U6SoLAass6Lbd3YRK7EARyG019k4"
  astrologer_channel: "2605944399"

log:
  level: "debug"
  sink: "stdout"

database:
  host: "postgres" 
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"