telegram:
  token: "7565405696:AAELJ7RISzLoqYPLvdvlBu8P6njDP0Gflk4"
  astrologer_channel: "2605944399"

log:
  level: "debug"
  sink: "stdout"

database:
  host: "postgres" 
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "postgres"
  sslmode: "disable"

# Добавьте эти настройки в конфигурацию

# Настройки API и веб-сервера
api:
  # Адрес для HTTP-сервера обработки нажатий на кнопку
  button_server_addr: ":8080"
  # Публичный URL для доступа к API (используется в PDF)
  public_url: "http://your-domain.com"
  # Путь для хранения PDF файлов
  pdf_storage_path: "./data/pdf"

# Настройки gRPC клиента для генерации PDF
grpc:
  # Адрес gRPC сервера
  server_addr: "localhost:50051"
  # Таймаут для gRPC запросов (в секундах)
  timeout: 30

# Настройки сервиса напоминаний
reminder:
  # Период проверки для отправки напоминаний (в минутах)
  check_period: 30
  # Время после взятия заказа в работу, через которое отправляется напоминание (в часах)
  reminder_time: 24