// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: internal/pkg/gen_v1/gen.proto

package gen_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Информация о месте рождения
type BirthCityInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`               // Город рождения
	Coordinates   string                 `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"` // Координаты города рождения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BirthCityInfo) Reset() {
	*x = BirthCityInfo{}
	mi := &file_internal_pkg_gen_v1_gen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BirthCityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BirthCityInfo) ProtoMessage() {}

func (x *BirthCityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_gen_v1_gen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BirthCityInfo.ProtoReflect.Descriptor instead.
func (*BirthCityInfo) Descriptor() ([]byte, []int) {
	return file_internal_pkg_gen_v1_gen_proto_rawDescGZIP(), []int{0}
}

func (x *BirthCityInfo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *BirthCityInfo) GetCoordinates() string {
	if x != nil {
		return x.Coordinates
	}
	return ""
}

// Запрос на генерацию консультации
type GenerateConsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                   // Имя клиента
	UserId                string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                                                 // ID пользователя
	BirthDate             string                 `protobuf:"bytes,3,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`                                        // Дата рождения
	BirthTime             string                 `protobuf:"bytes,4,opt,name=birth_time,json=birthTime,proto3" json:"birth_time,omitempty"`                                        // Время рождения
	BirthCity             *BirthCityInfo         `protobuf:"bytes,5,opt,name=birth_city,json=birthCity,proto3" json:"birth_city,omitempty"`                                        // Город рождения
	KnowBirthTime         bool                   `protobuf:"varint,6,opt,name=know_birth_time,json=knowBirthTime,proto3" json:"know_birth_time,omitempty"`                         // Флаг, знает ли пользователь точное время рождения
	SelectedConsultations string                 `protobuf:"bytes,7,opt,name=selected_consultations,json=selectedConsultations,proto3" json:"selected_consultations,omitempty"`    // Выбранный тип консультации
	PartnerName           string                 `protobuf:"bytes,8,opt,name=partner_name,json=partnerName,proto3" json:"partner_name,omitempty"`                                  // Имя партнера (для синастрии)
	PartnerBirthDate      string                 `protobuf:"bytes,9,opt,name=partner_birth_date,json=partnerBirthDate,proto3" json:"partner_birth_date,omitempty"`                 // Дата рождения партнера
	PartnerBirthTime      string                 `protobuf:"bytes,10,opt,name=partner_birth_time,json=partnerBirthTime,proto3" json:"partner_birth_time,omitempty"`                // Время рождения партнера
	PartnerBirthCity      *BirthCityInfo         `protobuf:"bytes,11,opt,name=partner_birth_city,json=partnerBirthCity,proto3" json:"partner_birth_city,omitempty"`                // Город рождения партнера
	PartnerKnowBirthTime  bool                   `protobuf:"varint,12,opt,name=partner_know_birth_time,json=partnerKnowBirthTime,proto3" json:"partner_know_birth_time,omitempty"` // Флаг, знает ли пользователь точное время рождения партнера
	ProductId             string                 `protobuf:"bytes,13,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`                                       // ID продукта/заказа
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerateConsRequest) Reset() {
	*x = GenerateConsRequest{}
	mi := &file_internal_pkg_gen_v1_gen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConsRequest) ProtoMessage() {}

func (x *GenerateConsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_gen_v1_gen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConsRequest.ProtoReflect.Descriptor instead.
func (*GenerateConsRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_gen_v1_gen_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateConsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GenerateConsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateConsRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *GenerateConsRequest) GetBirthTime() string {
	if x != nil {
		return x.BirthTime
	}
	return ""
}

func (x *GenerateConsRequest) GetBirthCity() *BirthCityInfo {
	if x != nil {
		return x.BirthCity
	}
	return nil
}

func (x *GenerateConsRequest) GetKnowBirthTime() bool {
	if x != nil {
		return x.KnowBirthTime
	}
	return false
}

func (x *GenerateConsRequest) GetSelectedConsultations() string {
	if x != nil {
		return x.SelectedConsultations
	}
	return ""
}

func (x *GenerateConsRequest) GetPartnerName() string {
	if x != nil {
		return x.PartnerName
	}
	return ""
}

func (x *GenerateConsRequest) GetPartnerBirthDate() string {
	if x != nil {
		return x.PartnerBirthDate
	}
	return ""
}

func (x *GenerateConsRequest) GetPartnerBirthTime() string {
	if x != nil {
		return x.PartnerBirthTime
	}
	return ""
}

func (x *GenerateConsRequest) GetPartnerBirthCity() *BirthCityInfo {
	if x != nil {
		return x.PartnerBirthCity
	}
	return nil
}

func (x *GenerateConsRequest) GetPartnerKnowBirthTime() bool {
	if x != nil {
		return x.PartnerKnowBirthTime
	}
	return false
}

func (x *GenerateConsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

// Ответ с сгенерированной консультацией
type GenerateConsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cons          []byte                 `protobuf:"bytes,1,opt,name=cons,proto3" json:"cons,omitempty"` // Байты PDF-документа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConsResponse) Reset() {
	*x = GenerateConsResponse{}
	mi := &file_internal_pkg_gen_v1_gen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConsResponse) ProtoMessage() {}

func (x *GenerateConsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_gen_v1_gen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConsResponse.ProtoReflect.Descriptor instead.
func (*GenerateConsResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_gen_v1_gen_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateConsResponse) GetCons() []byte {
	if x != nil {
		return x.Cons
	}
	return nil
}

var File_internal_pkg_gen_v1_gen_proto protoreflect.FileDescriptor

const file_internal_pkg_gen_v1_gen_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/pkg/gen_v1/gen.proto\x12\x06gen_v1\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\rBirthCityInfo\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12 \n" +
	"\vcoordinates\x18\x02 \x01(\tR\vcoordinates\"\xaf\x04\n" +
	"\x13GenerateConsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x03 \x01(\tR\tbirthDate\x12\x1d\n" +
	"\n" +
	"birth_time\x18\x04 \x01(\tR\tbirthTime\x124\n" +
	"\n" +
	"birth_city\x18\x05 \x01(\v2\x15.gen_v1.BirthCityInfoR\tbirthCity\x12&\n" +
	"\x0fknow_birth_time\x18\x06 \x01(\bR\rknowBirthTime\x125\n" +
	"\x16selected_consultations\x18\a \x01(\tR\x15selectedConsultations\x12!\n" +
	"\fpartner_name\x18\b \x01(\tR\vpartnerName\x12,\n" +
	"\x12partner_birth_date\x18\t \x01(\tR\x10partnerBirthDate\x12,\n" +
	"\x12partner_birth_time\x18\n" +
	" \x01(\tR\x10partnerBirthTime\x12C\n" +
	"\x12partner_birth_city\x18\v \x01(\v2\x15.gen_v1.BirthCityInfoR\x10partnerBirthCity\x125\n" +
	"\x17partner_know_birth_time\x18\f \x01(\bR\x14partnerKnowBirthTime\x12\x1d\n" +
	"\n" +
	"product_id\x18\r \x01(\tR\tproductId\"*\n" +
	"\x14GenerateConsResponse\x12\x12\n" +
	"\x04cons\x18\x01 \x01(\fR\x04cons2v\n" +
	"\vGeneratorV1\x12g\n" +
	"\fGenerateCons\x12\x1b.gen_v1.GenerateConsRequest\x1a\x1c.gen_v1.GenerateConsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/generate_consB\x15Z\x13internal/pkg/gen_v1b\x06proto3"

var (
	file_internal_pkg_gen_v1_gen_proto_rawDescOnce sync.Once
	file_internal_pkg_gen_v1_gen_proto_rawDescData []byte
)

func file_internal_pkg_gen_v1_gen_proto_rawDescGZIP() []byte {
	file_internal_pkg_gen_v1_gen_proto_rawDescOnce.Do(func() {
		file_internal_pkg_gen_v1_gen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_gen_v1_gen_proto_rawDesc), len(file_internal_pkg_gen_v1_gen_proto_rawDesc)))
	})
	return file_internal_pkg_gen_v1_gen_proto_rawDescData
}

var file_internal_pkg_gen_v1_gen_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_pkg_gen_v1_gen_proto_goTypes = []any{
	(*BirthCityInfo)(nil),        // 0: gen_v1.BirthCityInfo
	(*GenerateConsRequest)(nil),  // 1: gen_v1.GenerateConsRequest
	(*GenerateConsResponse)(nil), // 2: gen_v1.GenerateConsResponse
}
var file_internal_pkg_gen_v1_gen_proto_depIdxs = []int32{
	0, // 0: gen_v1.GenerateConsRequest.birth_city:type_name -> gen_v1.BirthCityInfo
	0, // 1: gen_v1.GenerateConsRequest.partner_birth_city:type_name -> gen_v1.BirthCityInfo
	1, // 2: gen_v1.GeneratorV1.GenerateCons:input_type -> gen_v1.GenerateConsRequest
	2, // 3: gen_v1.GeneratorV1.GenerateCons:output_type -> gen_v1.GenerateConsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pkg_gen_v1_gen_proto_init() }
func file_internal_pkg_gen_v1_gen_proto_init() {
	if File_internal_pkg_gen_v1_gen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_gen_v1_gen_proto_rawDesc), len(file_internal_pkg_gen_v1_gen_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_gen_v1_gen_proto_goTypes,
		DependencyIndexes: file_internal_pkg_gen_v1_gen_proto_depIdxs,
		MessageInfos:      file_internal_pkg_gen_v1_gen_proto_msgTypes,
	}.Build()
	File_internal_pkg_gen_v1_gen_proto = out.File
	file_internal_pkg_gen_v1_gen_proto_goTypes = nil
	file_internal_pkg_gen_v1_gen_proto_depIdxs = nil
}
