// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: internal/pkg/gen_v1/gen.proto

package gen_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeneratorV1_GenerateCons_FullMethodName = "/gen_v1.GeneratorV1/GenerateCons"
)

// GeneratorV1Client is the client API for GeneratorV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для генерации астрологических консультаций
type GeneratorV1Client interface {
	// Генерирует PDF-файл с консультацией
	GenerateCons(ctx context.Context, in *GenerateConsRequest, opts ...grpc.CallOption) (*GenerateConsResponse, error)
}

type generatorV1Client struct {
	cc grpc.ClientConnInterface
}

func NewGeneratorV1Client(cc grpc.ClientConnInterface) GeneratorV1Client {
	return &generatorV1Client{cc}
}

func (c *generatorV1Client) GenerateCons(ctx context.Context, in *GenerateConsRequest, opts ...grpc.CallOption) (*GenerateConsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateConsResponse)
	err := c.cc.Invoke(ctx, GeneratorV1_GenerateCons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratorV1Server is the server API for GeneratorV1 service.
// All implementations must embed UnimplementedGeneratorV1Server
// for forward compatibility.
//
// Сервис для генерации астрологических консультаций
type GeneratorV1Server interface {
	// Генерирует PDF-файл с консультацией
	GenerateCons(context.Context, *GenerateConsRequest) (*GenerateConsResponse, error)
	mustEmbedUnimplementedGeneratorV1Server()
}

// UnimplementedGeneratorV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeneratorV1Server struct{}

func (UnimplementedGeneratorV1Server) GenerateCons(context.Context, *GenerateConsRequest) (*GenerateConsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCons not implemented")
}
func (UnimplementedGeneratorV1Server) mustEmbedUnimplementedGeneratorV1Server() {}
func (UnimplementedGeneratorV1Server) testEmbeddedByValue()                     {}

// UnsafeGeneratorV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratorV1Server will
// result in compilation errors.
type UnsafeGeneratorV1Server interface {
	mustEmbedUnimplementedGeneratorV1Server()
}

func RegisterGeneratorV1Server(s grpc.ServiceRegistrar, srv GeneratorV1Server) {
	// If the following call pancis, it indicates UnimplementedGeneratorV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeneratorV1_ServiceDesc, srv)
}

func _GeneratorV1_GenerateCons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateConsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratorV1Server).GenerateCons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeneratorV1_GenerateCons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratorV1Server).GenerateCons(ctx, req.(*GenerateConsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneratorV1_ServiceDesc is the grpc.ServiceDesc for GeneratorV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneratorV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gen_v1.GeneratorV1",
	HandlerType: (*GeneratorV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateCons",
			Handler:    _GeneratorV1_GenerateCons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pkg/gen_v1/gen.proto",
}
